package com.alipay.sofa.ms.service;

import com.alipay.sofa.pressure.annotation.PressureField;
import com.alipay.sofa.pressure.annotation.PressureTest;

import java.io.Serializable;
import java.util.concurrent.atomic.AtomicLong;

@PressureTest
public class Request implements Serializable {

    private transient static AtomicLong id = new AtomicLong();

    public Request() {
    }

    public Request(String pressureId, String sellerNick, String skuId, String tradeId) {
        this.sellerNick = sellerNick;
        this.skuId = skuId;
        this.tradeId = tradeId;
        this.pressureId = pressureId;
        this.tid = id.incrementAndGet();
        this.type = "mock";
    }

    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.seller_nick
     *
     * @mbg.generated
     */
    @PressureField(name = "sellerNick")
    private String sellerNick;

    @PressureField(name = "skuId")
    private String skuId;

    @PressureField(name = "tradeId")
    private String tradeId;

    private String pressureId;

    public Long getTid() {
        return tid;
    }

    public void setTid(Long tid) {
        this.tid = tid;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSellerNick() {
        return sellerNick;
    }

    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick;
    }

    public String getPressureId() {
        return pressureId;
    }

    public void setPressureId(String pressureId) {
        this.pressureId = pressureId;
    }

    @Override
    public String toString() {

        StringBuffer buffer = new StringBuffer();

        buffer.append("pressureId=").append(this.pressureId);
        if (this.sellerNick != null) {
            buffer.append(", sellerNick=").append(this.sellerNick);
        }
        if (this.skuId != null) {
            buffer.append(", skuId=").append(this.skuId);
        }
        if (this.tradeId != null) {
            buffer.append(", tradeId=").append(this.tradeId);
        }

        if (this.tid != null) {
            buffer.append(", tid=").append(this.tid);
        }

        return buffer.toString();
    }
}