package com.alipay.sofa.ms.reply.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table jdp_tb_trade
 */
public class JdpTbTradeDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.tid
     *
     * @mbg.generated
     */
    private Long tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.seller_nick
     *
     * @mbg.generated
     */
    private String sellerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.buyer_nick
     *
     * @mbg.generated
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.modified
     *
     * @mbg.generated
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.jdp_hashcode
     *
     * @mbg.generated
     */
    private String jdpHashcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.jdp_created
     *
     * @mbg.generated
     */
    private Date jdpCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.jdp_modified
     *
     * @mbg.generated
     */
    private Date jdpModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.jdp_response
     *
     * @mbg.generated
     */
    private String jdpResponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.tid
     *
     * @return the value of jdp_tb_trade.tid
     *
     * @mbg.generated
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.tid
     *
     * @param tid the value for jdp_tb_trade.tid
     *
     * @mbg.generated
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.status
     *
     * @return the value of jdp_tb_trade.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.status
     *
     * @param status the value for jdp_tb_trade.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.type
     *
     * @return the value of jdp_tb_trade.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.type
     *
     * @param type the value for jdp_tb_trade.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.seller_nick
     *
     * @return the value of jdp_tb_trade.seller_nick
     *
     * @mbg.generated
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.seller_nick
     *
     * @param sellerNick the value for jdp_tb_trade.seller_nick
     *
     * @mbg.generated
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.buyer_nick
     *
     * @return the value of jdp_tb_trade.buyer_nick
     *
     * @mbg.generated
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.buyer_nick
     *
     * @param buyerNick the value for jdp_tb_trade.buyer_nick
     *
     * @mbg.generated
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.created
     *
     * @return the value of jdp_tb_trade.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.created
     *
     * @param created the value for jdp_tb_trade.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.modified
     *
     * @return the value of jdp_tb_trade.modified
     *
     * @mbg.generated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.modified
     *
     * @param modified the value for jdp_tb_trade.modified
     *
     * @mbg.generated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.jdp_hashcode
     *
     * @return the value of jdp_tb_trade.jdp_hashcode
     *
     * @mbg.generated
     */
    public String getJdpHashcode() {
        return jdpHashcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.jdp_hashcode
     *
     * @param jdpHashcode the value for jdp_tb_trade.jdp_hashcode
     *
     * @mbg.generated
     */
    public void setJdpHashcode(String jdpHashcode) {
        this.jdpHashcode = jdpHashcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.jdp_created
     *
     * @return the value of jdp_tb_trade.jdp_created
     *
     * @mbg.generated
     */
    public Date getJdpCreated() {
        return jdpCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.jdp_created
     *
     * @param jdpCreated the value for jdp_tb_trade.jdp_created
     *
     * @mbg.generated
     */
    public void setJdpCreated(Date jdpCreated) {
        this.jdpCreated = jdpCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.jdp_modified
     *
     * @return the value of jdp_tb_trade.jdp_modified
     *
     * @mbg.generated
     */
    public Date getJdpModified() {
        return jdpModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.jdp_modified
     *
     * @param jdpModified the value for jdp_tb_trade.jdp_modified
     *
     * @mbg.generated
     */
    public void setJdpModified(Date jdpModified) {
        this.jdpModified = jdpModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.jdp_response
     *
     * @return the value of jdp_tb_trade.jdp_response
     *
     * @mbg.generated
     */
    public String getJdpResponse() {
        return jdpResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.jdp_response
     *
     * @param jdpResponse the value for jdp_tb_trade.jdp_response
     *
     * @mbg.generated
     */
    public void setJdpResponse(String jdpResponse) {
        this.jdpResponse = jdpResponse;
    }
}