package com.alipay.sofa.ms.reply.mapper;

import com.alipay.sofa.ms.reply.entity.JdpTbTradeDO;
import com.alipay.sofa.ms.reply.entity.JdpTbTradeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JdpTbTradeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    long countByExample(JdpTbTradeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int deleteByExample(JdpTbTradeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int insert(JdpTbTradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int insertSelective(JdpTbTradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    List<JdpTbTradeDO> selectByExampleWithBLOBs(JdpTbTradeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    List<JdpTbTradeDO> selectByExample(JdpTbTradeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    JdpTbTradeDO selectByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JdpTbTradeDO record, @Param("example") JdpTbTradeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") JdpTbTradeDO record, @Param("example") JdpTbTradeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JdpTbTradeDO record, @Param("example") JdpTbTradeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JdpTbTradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(JdpTbTradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JdpTbTradeDO record);
}