package com.alipay.sofa.ms.mapper;

import com.alipay.sofa.ms.entity.EchoDO;
import com.alipay.sofa.ms.entity.EchoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EchoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    long countByExample(EchoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    int deleteByExample(EchoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    int insert(EchoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    int insertSelective(EchoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    List<EchoDO> selectByExample(EchoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    EchoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EchoDO record, @Param("example") EchoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EchoDO record, @Param("example") EchoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EchoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table echo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EchoDO record);
}